### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by digitalkaoz** [Daydreamer-riri/vite-react-ssg#19]
Hey,

im using https://github.com/xiaolin/react-image-gallery but it fails with this error:

``` 
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

    at renderElement (/home/projects/vitejs-vite-z1dmei/node_modules/react-dom/cjs/react-dom-server.node.development.js:6120:9)
    at renderNodeDestructiveImpl (/home/projects/vitejs-vite-z1dmei/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/home/projects/vitejs-vite-z1dmei/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderElement (/home/projects/vitejs-vite-z1dmei/node_modules/react-dom/cjs/react-dom-server.node.development.js:6048:9)
    at renderNodeDestructiveImpl (/home/projects/vitejs-vite-z1dmei/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/home/projects/vitejs-vite-z1dmei/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
    at renderIndeterminateComponent (/home/projects/vitejs-vite-z1dmei/node_modules/react-dom/cjs/react-dom-server.node.development.js:5852:7)
    at renderElement (/home/projects/vitejs-vite-z1dmei/node_modules/react-dom/cjs/react-dom-server.node.development.js:6023:7)
    at renderNodeDestructiveImpl (/home/projects/vitejs-vite-z1dmei/node_modules/react-dom/cjs/react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (/home/projects/vitejs-vite-z1dmei/node_modules/react-dom/cjs/react-dom-server.node.development.js:6153:14)
```

i created a repro here: https://stackblitz.com/edit/vitejs-vite-z1dmei
and created a ticket over there too (im not sure what goes wrong on what end). https://github.com/xiaolin/react-image-gallery/issues/799.

Thanks for looking into it. im not quite sure where the problem is

**Comment by Daydreamer-riri** [comment]
Hi @digitalkaoz , 经过我的尝试，我认为这可能是由于 `react-image-gallery` 构建版本对于服务端渲染的支持不太好。其源代码去除 vite 不兼容的 prop-type 相关代码后，似乎可以正常运行，但是其构建版本始终无法正常运行。

在我看了这个库有些古老，这可能也是其对服务端渲染支持不好的原因。或许你可以试试 https://swiperjs.com/react。

**Comment by digitalkaoz** [comment]
@Daydreamer-riri wow that was fast. Yeah i know its quite old, but its about porting an "old" react app onto vite+ssg, so i probably have to stick with it for a while (also its exactly fulfilling the use-cases and is lightweight).

what exactly did you change to make it work? i could create a PR over there

**Comment by Daydreamer-riri** [comment]
‌‌‌‌‌‌‌@digitalkaoz I've created a StackBlitz, which is currently functioning properly. You may refer to it.

https://stackblitz.com/edit/vitejs-vite-bkvqgk

**Comment by digitalkaoz** [comment]
ah i see, its simply the deprecated PropTypes stuff whats causing the problems. Thanks!

**Comment by digitalkaoz** [comment]
mh, can we make vite-react-ssg ignore those propTypes? its still a valid react feature right?

**Comment by Daydreamer-riri** [comment]
‌‌This is an issue with Vite. 

In my opinion, the inability to use `react-image-gallery` might be due to a problem with its build artifacts. Its output works fine in client-side rendering mode, but not during server-side rendering. It only works properly when using its source code directly, so I suspect that the build process of `react-image-gallery` might have compromised its own server-side rendering capabilities.

**Comment by digitalkaoz** [comment]
thanks, as the project is rather inactive from my POV, im gonna switch to another ssr capable library
