### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zouhangwithsweet** [Daydreamer-riri/vite-react-ssg#42]
Error:
```bash
[vite-react-ssg] Generating static loader data manifest...
file:///Users/sun/Desktop/work/homepage-starter/node_modules/.pnpm/vite-react-ssg@0.8.0_prettier@3.3.3_react-dom@18.2.0_react@18.2.0__react-router-dom@6.22.3_re_r4qwccl6tcbmj4sbhsu2awxnwi/node_modules/vite-react-ssg/dist/shared/vite-react-ssg.DObRRhiz.mjs:850
        throw new Error(`${gray("[vite-react-ssg]")} ${red(`Error on page: ${cyan(path)}`)}
              ^

Error: [vite-react-ssg] Error on page: /
TypeError: Cannot read properties of undefined (reading 'add')
    at r2.init (file:///Users/sun/Desktop/work/homepage-starter/.vite-react-ssg-temp/qfnrt4q6kz/main.mjs:1338:80)
    at r2.render (file:///Users/sun/Desktop/work/homepage-starter/.vite-react-ssg-temp/qfnrt4q6kz/main.mjs:1340:17)
    at finishClassComponent (/Users/sun/Desktop/work/homepage-starter/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:5729:31)

```

Reproduce:
https://github.com/fisand/homepage-starter/tree/fix-build

**Comment by zouhangwithsweet** [comment]
v0.6.3 works well

**Comment by Daydreamer-riri** [comment]
Thanks for the report. The problem has been positioned and will be released as soon as possible.

**Comment by Daydreamer-riri** [comment]
Fixed in v0.8.1.
