### ISSUE TITLE
ReferenceError: window is not defined in build

### ISSUE THREAD

**Issue by cinderblock** [Daydreamer-riri/vite-react-ssg#44]
I'm building a simple static site on GitHub Actions (for publishing on GH Pages) and am getting an error that requested I report it here.

Excerpt below. See the full project/build here: https://github.com/cinderblock/awesome-led-list/actions/runs/12092799259/job/33722975047

```log
ReferenceError: window is not defined
    at n (/home/runner/work/awesome-led-list/awesome-led-list/node_modules/fork-me-on-github/lib/index.js:1:9915)
    at i (/home/runner/work/awesome-led-list/awesome-led-list/node_modules/fork-me-on-github/lib/index.js:1:10003)
    at e.exports (/home/runner/work/awesome-led-list/awesome-led-list/node_modules/fork-me-on-github/lib/index.js:1:13575)
    at Object.<anonymous> (/home/runner/work/awesome-led-list/awesome-led-list/node_modules/fork-me-on-github/lib/index.js:1:8533)
    at r (/home/runner/work/awesome-led-list/awesome-led-list/node_modules/fork-me-on-github/lib/index.js:1:124)
    at Module.<anonymous> (/home/runner/work/awesome-led-list/awesome-led-list/node_modules/fork-me-on-github/lib/index.js:1:4231)
    at r (/home/runner/work/awesome-led-list/awesome-led-list/node_modules/fork-me-on-github/lib/index.js:1:124)
    at /home/runner/work/awesome-led-list/awesome-led-list/node_modules/fork-me-on-github/lib/index.js:1:923
    at Object.<anonymous> (/home/runner/work/awesome-led-list/awesome-led-list/node_modules/fork-me-on-github/lib/index.js:1:932)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:[337](https://github.com/cinderblock/awesome-led-list/actions/runs/12092799259/job/33722975047#step:4:338):24)
    at async build (file:///home/runner/work/awesome-led-list/awesome-led-list/node_modules/vite-react-ssg/dist/shared/vite-react-ssg.BdRX-qCI.mjs:789:88)
    at async Object.handler (file:///home/runner/work/awesome-led-list/awesome-led-list/node_modules/vite-react-ssg/dist/node/cli.mjs:51:5)
```

**Comment by Daydreamer-riri** [comment]
This is because fork-me-on-github does not support server-side rendering.

You can wrap it in [ClientOnly](https://github.com/Daydreamer-riri/vite-react-ssg?tab=readme-ov-file#clientonly).  Or open an issue in the fork-me-on-github repo.

**Comment by cinderblock** [comment]
Ah. What changes (high level) would be needed to make it SSR-able? Think it's worth updating, forking, finding a different package, or just extracting the source?

**Comment by Daydreamer-riri** [comment]
I don't understand this library. But I think it should have alternatives to support server-side rendering.

**Comment by cinderblock** [comment]
Thanks. I think I'll close this and play around with my options. Cheers.
